Fixes the bug about the closing time not being respected when several toasters are open
tjrexer/react-notifications pull request #51
Opened 2021-11-15 13:03 UTC by Clement83

fix #48

2021-11-15 13:07 UTC, Clement83 commented
Hello @tjrexer,

Maybe you want I push without generated code ? 

Tel me if you want I modify this PR.

Thank

2021-11-29 01:04 UTC, tjrexer requested changes
Remove the changes from `dist` & `lib`.  The `src` will be used to recompile both other directories after merge.

2021-11-29 13:17 UTC, Clement83 commented
@tjrexer  done

2021-12-11 18:29 UTC, tjrexer approved these changes

2021-12-11 18:29 UTC, merged